discordToken: "..."

adminIds:
  - 100000000000000000

invisible: false

aiConfig:
  preferredAiProvider: google

  boostImagePrompts: false

  maxDailyImages: 5
  
  ollama:
    endpoint: localhost:11434
    preferredModel: llama3.1
  
  openai:
    apiKey: sk-...
    preferredModel: gpt-5-nano
  
  antropic:
    apiKey: sk-ant-...
    preferredModel: claude-4-5-sonnet
  
  gemini:
    apiKey: ...
    preferredModel: gemini-2.5-flash
  
  elevenlabs:
    apiKey: ...
  
  orchestrator:
    preferredAiProvider: google
    preferredModel: gemini-2.5-flash

usersToId:
  name1: "<@100000000000000000>"
  name2: "<@200000000000000000>"
  name3: "<@300000000000000000>"

idToUsers:
  "000000000000000000": name1
  "100000000000000000": name2
  "200000000000000000": name3

mentionCooldown: 20

cooldownBypassList:
  - 100000000000000000

promptsPath: prompts.json
morningConfigsPath: morning_configs.json